contact_links:
  - name: ❗ 安全性問題
    url: https://zh.wikipedia.org/wiki/负责任的披露
    about:
      不要透過 issue 或公開討論說明任何安全性問題。嘗試透過私密方式和團隊負責人聯絡，例如信箱（evanlu361425@gmail.com）。
      我們會一起討論和解決這類問題，感謝！
  - name: 👻 其他
    url: https://github.com/evan361425/flutter-pos-system/discussions
    about: 其他所有問題都可以提出來討論
